people_attributes = {
    "Dwayne Johnson": "A male person, African-American and Samoan ethnicity, muscular, bald.",
    "Chris Hemsworth": "A male person, European descent, blond hair, blue eyes.",
    "Ryan Reynolds": "A male person, Canadian descent, brown hair, brown eyes.",
    "Chris Evans": "A male person, European descent, brown hair, blue eyes.",
    "George Clooney": "A male person, American descent, salt-and-pepper hair, brown eyes.",
    "Idris Elba": "A male person, British descent, muscular build, brown skin.",
    "Chris Pratt": "A male person, American descent, light brown hair, blue eyes.",
    "Daniel Craig": "A male person, British descent, short blond hair, blue eyes.",
    "Benedict Cumberbatch": "A male person, British descent, dark hair, blue eyes.",
    "Morgan Freeman": "A male person, African-American descent, bald head.",
    "Samuel L. Jackson": "A male person, African-American descent, shaved head.",
    "Christian Bale": "A male person, British descent, various appearances for different roles.",
    "Mark Ruffalo": "A male person, American descent, brown hair, brown eyes.",
    "Robert Pattinson": "A male person, British descent, messy brown hair.",
    "Vin Diesel": "A male person, American descent, bald, muscular build.",
    "Jason Momoa": "A male person, Native Hawaiian and European descent, muscular, long dark hair, beard.",
    "Tom Hardy": "A male person, British descent, various appearances for different roles.",
    "Kevin Hart": "A male person, African-American descent, charismatic personality.",
    "Michael B. Jordan": "A male person, African-American descent, muscular build.",
    "Adam Sandler": "A male person, American descent, dark hair.",
    "John Travolta": "A male person, American descent, various appearances for different roles.",
    "Matthew McConaughey": "A male person, American descent, distinctive Southern accent.",
    "Joaquin Phoenix": "A male person, American descent, dark hair, intense eyes.",
    "Justin Timberlake": "A male person, American descent, various appearances for different roles.",
    "Kanye West": "A male person, African-American descent, unique fashion style.",
    "Drake": "A male person, Canadian descent, distinctive beard.",
    "Ed Sheeran": "A male person, British descent, red hair, friendly demeanor.",
    "Cristiano Ronaldo": "A male person, Portuguese descent, muscular build.",
    "Lionel Messi": "A male person, Argentine descent, dark hair, remarkable football talent.",
    "LeBron James": "A male person, African-American descent, strong basketball physique.",
    "Roger Federer": "A male person, Swiss descent, graceful tennis style.",
    "Stephen Curry": "A male person, American descent, remarkable basketball shooting style.",
    "Jackie Chan": "A male person, Chinese descent, martial arts expertise, distinctive charisma.",
    "Jet Li": "A male person, Chinese descent, martial arts expertise, serious demeanor.",
    "Donnie Yen": "A male person, Chinese descent, martial arts expertise, charismatic presence.",
    "Tony Leung Chiu-wai": "A male person, Hong Kong descent, various appearances for different roles.",
    "Andy Lau": "A male person, Hong Kong descent, versatile career in entertainment.",
    "Chow Yun-fat": "A male person, Hong Kong descent, known for roles in action films.",
    "Huang Xiaoming": "A male person, Chinese descent, charming appearance.",
    "Wu Jing": "A male person, Chinese descent, known for martial arts skills.",
    "Chen Kun": "A male person, Chinese descent, various appearances for different roles.",
    "Meryl Streep": "A female person, American descent, distinguished acting career.",
    "Julia Roberts": "A female person, American descent, famous smile.",
    "Charlize Theron": "A female person, South African descent, blonde hair.",
    "Emma Watson": "A female person, British descent, brown hair, brown eyes.",
    "Halle Berry": "A female person, African-American descent, striking appearance.",
    "Cate Blanchett": "A female person, Australian descent, with a graceful and refined look.",
    "Reese Witherspoon": "A female person, American descent, charming smile.",
    "Gal Gadot": "A female person, Israeli descent, strong portrayal of Wonder Woman.",
    "Margot Robbie": "A female person, Australian descent, blonde hair.",
    "Emma Stone": "A female person, American descent, with red hair, a captivating smile, and expressive green eyes.",
    "Anne Hathaway": "A female person, American descent, with versatile and appealing features, including striking hazel eyes.",
    "Keira Knightley": "A female person, British descent, distinctive beauty, including her classic and captivating smile.",
    "Jessica Chastain": "A female person, American descent, red hair.",
    "Viola Davis": "A female person, African-American descent, powerful acting presence.",
    "Helen Mirren": "A female person, British descent, distinguished acting career.",
    "Gwyneth Paltrow": "A female person, American descent, successful acting career and lifestyle brand.",
    "Jennifer Aniston": "A female person, American descent, beautiful hair and charming smile..",
    "Drew Barrymore": "A female person, American descent, versatile acting career.",
    "Cameron Diaz": "A female person, American descent, successful acting career.",
    "Penélope Cruz": "A female person, Spanish descent, striking appearance.",
    "Salma Hayek": "A female person, Mexican descent, captivating presence.",
    "Rihanna": "A female person, distinctive fashion style.",
    "Beyoncé": "A female person, powerful voice.",
    "Taylor Swift": "A female person, distinctive country-pop style, signature blonde hair and expressive blue eyes.",
    "Katy Perry": "A female person, bold fashion style.",
    "Adele": "A female person, British descent, powerful voice.",
    "Lady Gaga": "A female person, unique fashion style.",
    "Madonna": "A female person, American descent, legendary music career, groundbreaking fashion style.",
    "Britney Spears": "A female person, pop icon status.",
    "Selena Gomez": "A female person, versatile talent.",
    "Ariana Grande": "A female person, Italian-American descent, powerful voice.",
    "Shakira": "A female person, Colombian descent, distinctive hips.",
    "Mariah Carey": "A female person, African-American and Irish descent, legendary vocal range.",
    "Fan Bingbing": "A female person, Chinese descent, successful acting career, fashion icon status.",
    "Gong Li": "A female person, Chinese descent, elegant presence.",
    "Zhang Ziyi": "A female person, Chinese descent, martial arts skills.",
    "Zhao Wei": "A female person, Chinese descent, versatile career in entertainment.",
    "Liu Yifei": "A female person, Chinese descent, Disney princess role.",
    "Tang Wei": "A female person, Chinese descent, striking presence.",
    "Shu Qi": "A female person, Chinese descent, charismatic presence.",
    "Yang Mi": "A female person, Chinese descent, fashionable image.",
    "Angelababy": "A female person, Chinese descent, fashion icon status.",
    "Zhou Xun": "A female person, Chinese descent, diverse filmography."
}
